/**
 * THE DEFINITIVE UKCFA SYSTEM SCHEMA DICTIONARY REGISTER
 * Automatically supports all 12 operational stored procedures and background data tables.
 */
const DB_FIELD_DICTIONARY = {
    // 1. Core CRM Stored Procedures Parameters & Metrics
    "PROVISIONED": { title: "Provisions Gross Volume", width: 140, sorter: "number", hozAlign: "right", formatter: "money", formatterParams: { precision: 0 } },
    "CLOSED": { title: "Accounts Closed Volume", width: 140, sorter: "number", hozAlign: "right", formatter: "money", formatterParams: { precision: 0 } },
    "TOTAL_CONNECTIONS": { title: "Active Inventory Lines", width: 140, sorter: "number", hozAlign: "right", formatter: "money", formatterParams: { precision: 0 } },
    "OA_SSA": { title: "Operational Area (SSA)", width: 160, sorter: "string" },
    "COMPUTED_OA_SSA": { title: "Operational Area", width: 150, sorter: "string" },
    "MAPPED_GP_NAME": { title: "Mapped GP Name", width: 160, sorter: "string" },

    // 2. Transaction Records Tables (ftth_provisioning & ftth_disconnection)
    "CRM_ORDER_ID": { title: "CRM Order ID Reference", width: 150, sorter: "string" },
    "TEL_NUM": { title: "Telephone Service Line", width: 130, sorter: "string" },
    "OLT_IP": { title: "Routing Gateway (OLT IP)", width: 130, sorter: "string" },
    "SSA": { title: "Operational Area (SSA)", width: 140, sorter: "string" },
    "SERVICE_TYPE": { title: "Service Category Class", width: 140, sorter: "string" },
    "CIRCLE": { title: "LSA Core Circle", width: 100, sorter: "string" },
    "EXCHANGE": { title: "Assigned Exchange", width: 130, sorter: "string" },
    "MAINT_FRAN": { title: "Maintenance Franchisee", width: 160, sorter: "string" },
    "OLT_OWNER": { title: "Hardware Owner", width: 120, sorter: "string" },
    "DATED": { title: "CRM Finalized Timestamp", width: 150, sorter: "datetime", hozAlign: "center" },
    "ORDER_SUB_TYPE": { title: "Order Sub-Type Action", width: 160, sorter: "string", cssClass: "text-danger fw-semibold" },

    // 3. Operational Active Records Data (working_ftth & working_ftth_08062026)
    "EXG": { title: "Assigned Exchange", width: 130, sorter: "string" },
    "PHONE_NO": { title: "Broadband Phone No.", width: 130, sorter: "string" },
    "BA": { title: "Business Area (BA)", width: 120, sorter: "string" },
    "INST_DATE": { title: "Installation Timestamp", width: 150, sorter: "datetime", hozAlign: "center" },
    "CUST_NAME": { title: "Registered Customer", width: 180, sorter: "string" },
    "CUST_ADD": { title: "Registered Address", width: 220, sorter: "string", formatter: "textarea" },
    "PLAN": { title: "Assigned Tariff Plan", width: 160, sorter: "string" },
    "MOBILE_NO": { title: "Contact Mobile", width: 120, sorter: "number" },
    "EMAIL": { title: "Registered Email", width: 160, sorter: "string" },
    "OLT_NAME": { title: "OLT Device Descriptor", width: 160, sorter: "string" },
    "OLT_VENDOR": { title: "Hardware Vendor", width: 130, sorter: "string" },
    "ONT_ACQUISITION_TYPE": { title: "ONT Sourcing Type", width: 150, sorter: "string" },

    // 4. Master Broadband Infrastructure Tables (olt & bbm)
    "OLT_ID": { title: "OLT Global ID Unique", width: 140, sorter: "string" },
    "LOCATION": { title: "Physical Site Location", width: 180, sorter: "string" },
    "TYPE": { title: "Deployment Mode", width: 110, sorter: "string" },
    "OA": { title: "Operational Area Name", width: 110, sorter: "string" },
    "SDCA": { title: "SDCA Region Mapping", width: 120, sorter: "string" },
    "DISTRICT": { title: "District Name", width: 120, sorter: "string" },
    "BLOCK": { title: "Block Name", width: 120, sorter: "string" },
    "WKG_CONN": { title: "Live Working Lines", width: 110, sorter: "number", hozAlign: "right" },
    "PORTS": { title: "Total Equipped Ports", width: 110, sorter: "number", hozAlign: "right" },
    "FRANCHISEE": { title: "Franchisee Name", width: 180, sorter: "string" },
    "FRANCHISEE_ID": { title: "Franchisee Account ID", width: 140, sorter: "string" },
    "FRANCHISEE_USERNAME": { title: "Franchisee Portal User", width: 150, sorter: "string" },
    "MAKE": { title: "Manufacturer Brand", width: 120, sorter: "string" },
    "LOCATION_TYPE": { title: "Location Node Class", width: 130, sorter: "string" },
    "BSNLEXCH_NAME": { title: "Associated BSNL Exchange", width: 160, sorter: "string" },
    "CLUSTER_ID": { title: "Operational Cluster ID", width: 130, sorter: "string" },
    "POWER_BACKUP": { title: "Power Backup Status", width: 130, sorter: "string" },
    "BACKUP_DURATION": { title: "Backup Battery Runtime", width: 140, sorter: "string" },
    "MEDIA_SITE": { title: "Site Media Categorization", width: 140, sorter: "string" },
    "CONNECTIVITY": { title: "Uplink Type Descriptor", width: 140, sorter: "string" },
    "BBM_NAME": { title: "BBM Manager Pointer", width: 160, sorter: "string" },
    "BBM_MOBILE": { title: "BBM Mobile Contact", width: 120, sorter: "string" },
    "BBM_DESIGNATION": { title: "BBM Designation Rank", width: 130, sorter: "string" },
    "BBM_EMAIL": { title: "BBM Office Email", width: 160, sorter: "string" },
    "BBM_USERNAME": { title: "BBM System User ID", width: 130, sorter: "string" },
    "LAT": { title: "Latitude Coordinate", width: 110, sorter: "number" },
    "LNG": { title: "Longitude Coordinate", width: 110, sorter: "number" },
    "LOCATION_LATLONG": { title: "Lat/Long Geostring", width: 130, sorter: "string" },
    "URBAN_RURAL": { title: "Territory Class", width: 110, sorter: "string" },
    "BNU_OLTE_YN": { title: "BNU OLTE Co-located", width: 130, sorter: "string", hozAlign: "center" },
    "BACKHAUL_MEDIA": { title: "Backhaul Media Type", width: 140, sorter: "string" },
    "BACKHAUL_NODE": { title: "Backhaul Node Profile", width: 140, sorter: "string" },
    "BACKHAUL_NODE_TYPE": { title: "Backhaul Node Class", width: 140, sorter: "string" },
    "TIP_LOCAL_LEAD": { title: "Local TIP Lead Assignment", width: 140, sorter: "string" },
    "MAAN_MIGRATED": { title: "MAAN Network Migrated", width: 140, sorter: "string", hozAlign: "center" },
    "MANN_NODE": { title: "MAAN Dedicated Node", width: 140, sorter: "string" },
    "CLOSE_DATE": { title: "Node Decommission Date", width: 140, sorter: "string" },
    "BNG_IP": { title: "Gateway BNG IP Address", width: 130, sorter: "string" },
    "VLAN": { title: "Configured Service VLAN", width: 90, sorter: "number" },
    "AVL": { title: "Network Availability %", width: 110, sorter: "number", hozAlign: "right" },
    "REBOOT": { title: "System Reboot Cycles", width: 110, sorter: "number", hozAlign: "right" },
    "STATUS": { title: "Active Operational Status", width: 100, sorter: "string", hozAlign: "center" },
    "BBM_EMAIL": { title: "BBM Corporate Email", width: 160, sorter: "string" },
    "AREA": { title: "BBM Assigned Area Scope", width: 200, sorter: "string", formatter: "textarea" },
    "ACTIVE": { title: "Profile Active Flag", width: 100, sorter: "string", hozAlign: "center" },

    // 5. Geographic Administrative Assets Directory Mapping Tables (gp & bnu_ftth)
    "STATE": { title: "State Province", width: 110, sorter: "string" },
    "BLOCK_LGD_CODE": { title: "Block LGD Code Unique", width: 130, sorter: "string" },
    "GP_NAME": { title: "Gram Panchayat", width: 150, sorter: "string" },
    "LGD_CODE": { title: "LGD Code Reference", width: 120, sorter: "string" },
    "PHASE": { title: "Implementation Phase", width: 110, sorter: "string" },
    "VIL": { title: "Village Index Mapping", width: 110, sorter: "string" },
    "HH": { title: "Household Count Metrics", width: 120, sorter: "number", hozAlign: "right" },
    "POP": { title: "Total Local Population", width: 120, sorter: "number", hozAlign: "right" },
    "INT_DATE": { title: "Integration Log Date", width: 120, sorter: "string" },
    "COV": { title: "Coverage Mapping Node", width: 110, sorter: "string" },
    "FFTH_NUM": { title: "Primary FTTH Number Block", width: 140, sorter: "string" },
    "TOTAL_OPEN": { title: "Lifetime Opened Gross", width: 130, sorter: "number", hozAlign: "right" },
    "TOTAL_CLOSE": { title: "Lifetime Closed Gross", width: 130, sorter: "number", hozAlign: "right" },
    "TOTAL_FTTH": { title: "Net Active FTTH Lines", width: 130, sorter: "number", hozAlign: "right" },
    "ABP_FTTH_OPEN": { title: "ABP Window Opened", width: 130, sorter: "number", hozAlign: "right" },
    "ABP_FTTH_CLOSE": { title: "ABP Window Closed", width: 130, sorter: "number", hozAlign: "right" },
    "ABP_TOTAL_FTTH": { title: "ABP Net Active Base", width: 130, sorter: "number", hozAlign: "right" },
    "FTTH_PARTNER_NAME": { title: "Associated LCO Partner", width: 180, sorter: "string" },
    "BNU": { title: "BNU Assignment ID", width: 110, sorter: "string" },
    "BBM": { title: "BBM Assigned Track", width: 150, sorter: "string" },
    "GP_TYPE": { title: "GP Classification Type", width: 130, sorter: "string", hozAlign: "center" },
    "SAMRIDH": { title: "Samridh Project Status", width: 120, sorter: "string", hozAlign: "center" },
    "ONT_MAC_ID": { title: "ONT Hardware MAC ID", width: 150, sorter: "string" },
    "BNU_MOBILE": { title: "LCO Partner Mobile", width: 120, sorter: "string" },
    "BNU_CODE": { title: "LCO Partner Vendor Code", width: 140, sorter: "string" },
    "BNU_TYPE": { title: "LCO Operational Classification", width: 140, sorter: "string" },
    "PAN_NUMBER": { title: "Corporate PAN Number", width: 130, sorter: "string" },
    "VILLAGE_NAME": { title: "Village Territory Name", width: 150, sorter: "string" },
    "VILLAGE_CODE": { title: "Village Census LGD Code", width: 140, sorter: "string" },
    "CONNECTION_DATE": { title: "Provision Date Log", width: 140, sorter: "datetime", hozAlign: "center" },
    "CUSTOMER_ID": { title: "CRM Billing Account ID", width: 150, sorter: "string" },
    "USER_TYPE": { title: "Commercial User Group", width: 140, sorter: "string" },
    "USER_TYPE_CATEGORY": { title: "User Class Category", width: 140, sorter: "string" },
    "USER_TYPE_SUB_CATEGORY": { title: "User Class Sub-Category", width: 150, sorter: "string" },
    "CUSTOMER_INSTITUTION_NAME": { title: "Enterprise Entity Name", width: 180, sorter: "string" },
    "CUSTOMER_TYPE": { title: "Subscriber Class Segment", width: 140, sorter: "string" },
    "CONTACT_NO": { title: "Subscriber Mobile Contact", width: 120, sorter: "number" },
    "ADDRESS": { title: "Physical Premise Address", width: 220, sorter: "string", formatter: "textarea" },
    "GENDER": { title: "Gender Attribute", width: 90, sorter: "string", hozAlign: "center" },
    "LATITUDE": { title: "Geom Latitude Mapping", width: 120, sorter: "number" },
    "LONGITUDE": { title: "Geom Longitude Mapping", width: 120, sorter: "number" },
    "BB_TARIFF_ID": { title: "Billing Tariff ID", width: 110, sorter: "string" },
    "TARIFF_PLAN": { title: "Configured Speed Plan", width: 160, sorter: "string" },
    "FIXED_CHARGES": { title: "Plan Monthly Fixed Costs", width: 130, sorter: "number", hozAlign: "right" },
    "BILLED_MONTHS": { title: "Total Retention Months", width: 130, sorter: "number", hozAlign: "right" },
    "BANDWIDTH_PROVIDED": { title: "Provisioned Port Speed", width: 130, sorter: "string" },
    "CATEGORY": { title: "Core Subscriber Line Class", width: 130, sorter: "string" },
    "IMPLEMENTATION_AGENCY": { title: "Nodal Rollout Entity", width: 140, sorter: "string" },
    "CURRENT_STATUS": { title: "Account Operational State", width: 130, sorter: "string", hozAlign: "center" },
    "DISCONNECTION_DATE": { title: "Closure Request Timestamp", width: 140, sorter: "datetime", hozAlign: "center" },
    "DATA_CONSUMED_GB": { title: "Monthly Usage Metrics (GB)", width: 140, sorter: "number", hozAlign: "right" },
    "LAST_PAID_AMOUNT_RS": { title: "Last Invoice Paid (Rs.)", width: 130, sorter: "number", hozAlign: "right" },
    "LAST_PAID_DATE": { title: "Last Payment Timestamp", width: 140, sorter: "datetime", hozAlign: "center" },
    "SOURCE_STATE": { title: "Origin State Node Reference", width: 140, sorter: "string" },
    "SOURCE_DISTRICT": { title: "Origin District Node Reference", width: 140, sorter: "string" },
    "SOURCE_BLOCK": { title: "Origin Block Node Reference", width: 140, sorter: "string" },
    "SOURCE_GP_NAME": { title: "Origin GP Node Reference", width: 140, sorter: "string" },
    "SOURCE_VILLAGE": { title: "Origin Village Node Reference", width: 140, sorter: "string" },
    "SOURCE_GP_CODE": { title: "Origin GP LGD Reference", width: 140, sorter: "string" },

    // 6. Network Infrastructure Health Metrics & Fault Tracking (FAULTS)
    "FAULT_ID": { title: "Fault Ticket Identifier", width: 140, sorter: "string" },
    "FAULT_DATE": { title: "Outage Trigger Date", width: 120, sorter: "date", hozAlign: "center" },
    "FAULT_TIME": { title: "Outage Trigger Time", width: 110, sorter: "time", hozAlign: "center" },
    "ROUTE_BRIEF": { title: "Affected Fiber Route", width: 180, sorter: "string" },
    "MAINTAINED_BY": { title: "SLA Restoration Party", width: 140, sorter: "string" },
    "ROUTE_OWNER": { title: "Fiber Asset Owner", width: 130, sorter: "string" },
    "LOCATION_BRIEF": { title: "Proximity Failure Zone", width: 160, sorter: "string" },
    "FAULT_DESCRIPTION": { title: "Root Cause Classification", width: 180, sorter: "string", formatter: "textarea" },
    "ROUTE_RING_LINEAR": { title: "Topological Route Class", width: 130, sorter: "string" },
    "ELEMENT_AFFECTED": { title: "Impacted Network Elements", width: 180, sorter: "string", formatter: "textarea" },
    "FRT_ASSIGNED": { title: "Dispatched FRT Team ID", width: 140, sorter: "string" },
    "ETR": { title: "Estimated Time to Restore", width: 130, sorter: "string" },
    "FAULT_TYPE": { title: "Severity Classification", width: 130, sorter: "string", hozAlign: "center" },
    "RESTORATION_DATE": { title: "SLA Clearance Date", width: 120, sorter: "date", hozAlign: "center" },
    "RESTORATION_TIME": { title: "SLA Clearance Time", width: 110, sorter: "time", hozAlign: "center" },
    "RESTORATION_BRIEF": { title: "Resolution Action Taken", width: 180, sorter: "string", formatter: "textarea" },
    "CREATED_BY": { title: "Operator Logging Profile", width: 140, sorter: "string" },

    // 7. Base Core Entities Validation Tables (block, oa, user, users)
    "ID": { title: "Internal Row Index", width: 90, sorter: "number" },
    "CODE": { title: "Administrative Code ID", width: 120, sorter: "string" },
    "TE_NAME": { title: "Telecom Exchange Target Name", width: 160, sorter: "string" },
    "LAT_LNG": { title: "Lat/Long Comma Vector", width: 130, sorter: "string" },
    "ENTITY_CODE": { title: "Asset Entity Code", width: 120, sorter: "string" },
    "RENTED": { title: "Premises Tenure Type", width: 130, sorter: "string" },
    "BHQ_STATUS": { title: "Block HQ Connectivity Status", width: 140, sorter: "string", hozAlign: "center" },
    "BACKHAUL": { title: "Backhaul Architecture Link", width: 140, sorter: "string" },
    "RING": { title: "Ring Protection Mapping", width: 120, sorter: "string" },
    "INFRA": { title: "Infrastructure Deployment Status", width: 130, sorter: "string" },
    "TS_SITE_ID": { title: "Transmission Tower Site ID", width: 140, sorter: "string" },
    "LSA": { title: "Licensed Service Area Zone", width: 140, sorter: "string" },
    "TOWN_VILLAGE": { title: "Settlement Territory Location", width: 150, sorter: "string" },
    "SITE_CATEGORY": { title: "Tower Classification Group", width: 140, sorter: "string" },
    "SITE_TYPE": { title: "Tower Structural Type", width: 130, sorter: "string" },
    "TSP_SITE_ID": { title: "Telecom Provider Site ID", width: 140, sorter: "string" },
    "TSP_SITE_NAME": { title: "Telecom Provider Site Name", width: 150, sorter: "string" },
    "IP_NAME": { title: "Infrastructure Provider Name", width: 150, sorter: "string" },
    "IP_SITE_ID": { title: "Infra Provider Site ID", width: 140, sorter: "string" },
    "IP_SITE_NAME": { title: "Infra Provider Site Name", width: 150, sorter: "string" },
    "TOWER_HEIGHT": { title: "Tower Height AGL (m)", width: 130, sorter: "number", hozAlign: "right" },
    "BUILDING_HEIGHT": { title: "Building Structure Height", width: 140, sorter: "number", hozAlign: "right" },
    "PINCODE": { title: "Postal Zip Code Vector", width: 110, sorter: "number", hozAlign: "center" },
    "FULL_SITE_ADDRESS": { title: "Full Infrastructure Address", width: 220, sorter: "string", formatter: "textarea" },
    "MEDIA": { title: "Last-Mile Core Media Link", width: 130, sorter: "string" },
    "EXCH_CODE": { title: "Exchange Boundary Identifier", width: 130, sorter: "string" },
    "EXCH_NAME": { title: "Exchange Core Working Descriptor", width: 160, sorter: "string" },
    "PRESENT_USER_ID": { title: "Currently Logged Personnel ID", width: 150, sorter: "string" },
    "KMZ_FILENAME": { title: "Geospatial KMZ Layer File", width: 160, sorter: "string" },
    "OWNER": { title: "Asset Legal Proprietor", width: 130, sorter: "string" },
    "START_LAT": { title: "Link Origin Latitude Coordinate", width: 130, sorter: "number" },
    "START_LNG": { title: "Link Origin Longitude Coordinate", width: 130, sorter: "number" },
    "END_LAT": { title: "Link Termination Latitude", width: 130, sorter: "number" },
    "END_LNG": { title: "Link Termination Longitude", width: 130, sorter: "number" },
    "COORDINATES_COUNT": { title: "Polyline Node Points Count", width: 130, sorter: "number", hozAlign: "right" },
    "USER_ID": { title: "Application Account Username", width: 140, sorter: "string" },
    "NAME": { title: "Personnel Full Identity", width: 150, sorter: "string" },
    "ROLE": { title: "Access Control Layer Role", width: 110, sorter: "string", hozAlign: "center" },
    "DESIGNATION": { title: "Personnel Structural Title", width: 140, sorter: "string" },
    "MOBILE": { title: "Personnel Mobile Contact", width: 120, sorter: "string" },
    "username": { title: "Portal Username", width: 130, sorter: "string" },
    "role": { title: "ACL Access Role", width: 110, sorter: "string", hozAlign: "center" },
    "oa": { title: "Regional OA Boundary Scope", width: 120, sorter: "string" },
    "name": { title: "User Account Name Label", width: 140, sorter: "string" },
    "email": { title: "User Account Primary Email", width: 150, sorter: "string" },
    "mobile": { title: "User Account Phone Line", width: 120, sorter: "string" },
    "designation": { title: "User Corporate Designation", width: 140, sorter: "string" },
    "photo_path": { title: "Avatar File Path Workspace", width: 160, sorter: "string" }
};