CREATE TABLE IF NOT EXISTS `BNU_FTTH` (

    `OLT_IP`                    VARCHAR(50),
    `ONT_MAC_ID`                VARCHAR(20),
    `BNU_NAME`                  VARCHAR(255),
    `BNU_MOBILE`                VARCHAR(20),
    `BNU_CODE`                  VARCHAR(100),
    `BNU_TYPE`                  VARCHAR(50),
    `PAN_NUMBER`                VARCHAR(20),
    `STATE`                     VARCHAR(100),
    `DISTRICT`                  VARCHAR(100),
    `BLOCK`                     VARCHAR(100),
    `GP_NAME`                   VARCHAR(255),
    `GP_CODE`                   VARCHAR(50),
    `VILLAGE_NAME`              VARCHAR(255),
    `VILLAGE_CODE`              VARCHAR(50),
    `CONNECTION_DATE`           DATE,
    `CUSTOMER_ID`               VARCHAR(255),
    `USER_TYPE`                 VARCHAR(100),
    `USER_TYPE_CATEGORY`        VARCHAR(100),
    `USER_TYPE_SUB_CATEGORY`    VARCHAR(100),
    `CUSTOMER_INSTITUTION_NAME` VARCHAR(255),
    `CUSTOMER_TYPE`             VARCHAR(100),
    `CONTACT_NO`                VARCHAR(20),
    `ADDRESS`                   TEXT,
    `GENDER`                    VARCHAR(20),
    `LATITUDE`                  VARCHAR(30),
    `LONGITUDE`                 VARCHAR(30),
    `BB_TARIFF_ID`              VARCHAR(100),
    `TARIFF_PLAN`               VARCHAR(255),
    `FIXED_CHARGES`             VARCHAR(50),
    `BILLED_MONTHS`             VARCHAR(50),
    `BANDWIDTH_PROVIDED`        VARCHAR(50),
    `CATEGORY`                  VARCHAR(100),
    `IMPLEMENTATION_AGENCY`     VARCHAR(100),
    `CURRENT_STATUS`            VARCHAR(100),
    `DISCONNECTION_DATE`        DATE,
    `DATA_CONSUMED_GB_APR2026`  VARCHAR(50),
    `LAST_PAID_AMOUNT_RS`       VARCHAR(50),
    `LAST_PAID_DATE`            DATE,
    `SOURCE_STATE`              VARCHAR(100),
    `SOURCE_DISTRICT`           VARCHAR(100),
    `SOURCE_BLOCK`              VARCHAR(100),
    `SOURCE_GP_NAME`            VARCHAR(255),
    `SOURCE_VILLAGE`            VARCHAR(255),
    `SOURCE_GP_CODE`            VARCHAR(50),
)
    -- INDEX `idx_state`           (`STATE`),
    -- INDEX `idx_district`        (`DISTRICT`),
    -- INDEX `idx_current_status`  (`CURRENT_STATUS`),
    -- INDEX `idx_connection_date` (`CONNECTION_DATE`),
    -- INDEX `idx_bnu_code`        (`BNU_CODE`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;